=== Ishaq74/atomic/src/lib/starwind/config-schema.json
{"$schema":"http://json-schema.org/draft-07/schema#","title":"Starwind UI Configuration","description":"Configuration schema for Starwind UI components and settings","type":"object","properties":{"$schema":{"type":"string","description":"The schema the configuration adheres to","default":"https://starwind.dev/config-schema.json"},"tailwind":{"type":"object","description":"Tailwind CSS configuration settings","properties":{"css":{"type":"string","description":"Path to the Starwind CSS file","default":"src/styles/starwind.css"},"baseColor":{"type":"string","description":"Base color theme for the UI components","enum":["slate","gray","zinc","neutral","stone"],"default":"neutral"},"cssVariables":{"type":"boolean","description":"Whether to use CSS variables for theming. Currently only CSS variables are supported.","default":true}},"required":["css","baseColor","cssVariables"],"additionalProperties":false},"componentDir":{"type":"string","description":"Directory where Starwind UI components are located","default":"src/components"},"utilsDir":{"type":"string","description":"Directory where Starwind UI utilities are located","default":"src/lib/utils"},"components":{"type":"array","description":"List of Starwind UI components added to your project","items":{"type":"object","properties":{"name":{"type":"string","description":"Name of the component"},"version":{"type":"string","description":"Version of the component"}},"required":["name","version"],"additionalProperties":false},"default":[]}},"required":["tailwind","componentDir","components"],"additionalProperties":false}

=== Ishaq74/atomic/starwind.config.json
{
  "$schema": "./src/lib/starwind/config-schema.json",
  "tailwind": {
    "css": "@styles/global.css",
    "baseColor": "stone",
    "cssVariables": true
  },
  "componentDir": "@atoms",
  "utilsDir": "@starwind",
  "components": [
    {
      "name": "button",
      "version": "2.3.2"
    },
    {
      "name": "separator",
      "version": "1.0.1"
    },
    {
      "name": "input",
      "version": "1.3.2"
    },
    {
      "name": "textarea",
      "version": "1.3.2"
    },
    {
      "name": "dialog",
      "version": "1.4.4"
    },
    {
      "name": "sheet",
      "version": "1.1.2"
    },
    {
      "name": "skeleton",
      "version": "1.2.1"
    },
    {
      "name": "tooltip",
      "version": "1.5.0"
    },
    {
      "name": "toggle",
      "version": "1.0.2"
    },
    {
      "name": "accordion",
      "version": "1.3.4"
    },
    {
      "name": "alert",
      "version": "1.3.1"
    },
    {
      "name": "alert-dialog",
      "version": "1.0.4"
    },
    {
      "name": "aspect-ratio",
      "version": "1.0.2"
    },
    {
      "name": "avatar",
      "version": "1.2.2"
    },
    {
      "name": "badge",
      "version": "1.4.2"
    },
    {
      "name": "breadcrumb",
      "version": "1.1.2"
    },
    {
      "name": "button-group",
      "version": "1.0.1"
    },
    {
      "name": "card",
      "version": "2.0.1"
    },
    {
      "name": "carousel",
      "version": "1.0.3"
    },
    {
      "name": "checkbox",
      "version": "1.4.2"
    },
    {
      "name": "collapsible",
      "version": "1.0.1"
    },
    {
      "name": "dropdown",
      "version": "1.3.1"
    },
    {
      "name": "dropzone",
      "version": "1.2.3"
    },
    {
      "name": "image",
      "version": "1.0.1"
    },
    {
      "name": "input-group",
      "version": "1.0.0"
    },
    {
      "name": "input-otp",
      "version": "1.0.2"
    },
    {
      "name": "item",
      "version": "1.0.2"
    },
    {
      "name": "kbd",
      "version": "1.0.1"
    },
    {
      "name": "label",
      "version": "1.2.1"
    },
    {
      "name": "native-select",
      "version": "1.0.0"
    },
    {
      "name": "pagination",
      "version": "3.0.3"
    },
    {
      "name": "popover",
      "version": "1.0.0"
    },
    {
      "name": "progress",
      "version": "1.1.2"
    },
    {
      "name": "prose",
      "version": "1.0.1"
    },
    {
      "name": "radio-group",
      "version": "1.2.5"
    },
    {
      "name": "select",
      "version": "1.8.4"
    },
    {
      "name": "sidebar",
      "version": "1.0.1"
    },
    {
      "name": "slider",
      "version": "1.0.1"
    },
    {
      "name": "spinner",
      "version": "1.0.1"
    },
    {
      "name": "switch",
      "version": "1.3.2"
    },
    {
      "name": "table",
      "version": "1.1.1"
    },
    {
      "name": "tabs",
      "version": "1.4.2"
    },
    {
      "name": "theme-toggle",
      "version": "1.0.1"
    },
    {
      "name": "toast",
      "version": "1.0.1"
    },
    {
      "name": "video",
      "version": "1.0.1"
    }
  ]
}
